# Generated by Django 5.0.2 on 2024-04-14 16:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_user_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posting',
            name='likes',
        ),
        migrations.AddField(
            model_name='posting',
            name='likes',
            field=models.ManyToManyField(related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
