# Generated by Django 5.0.2 on 2024-04-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_remove_posting_likes_posting_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
